fix nestjs sdk (#8166)
## Summary

* fixes node.js sdk causing process to hang when ctrl+c terminated
* fixes http instrumentation breaking nestjs and other libraries (error
1)
* simplifies dependency patches and fixes sdk configuration to causing
opentelemetry export error (error 2)

error 1:
```bash
[Highlight Node.js 148.137s] - {client} failed to flush:  TypeError: Cannot read properties of undefined (reading 'add')
    at HttpInstrumentation._startHttpSpan ([REDACTED]/node_modules/@highlight-run/node/node_modules/@opentelemetry/instrumentation-http/build/src/http.js:473:28)
```

error 2:
```bash
[REDACTED]/sdk/highlight-node/node_modules/@opentelemetry/otlp-exporter-base/build/esm/platform/node/util.js:55
        if (req.destroyed) {
                ^
TypeError: Cannot read properties of undefined (reading 'destroyed')
```

## How did you test this change?

nestjs
![Screenshot from 2024-04-02
16-02-51](https://github.com/highlight/highlight/assets/1351531/bfa34f42-8500-40a5-8188-036a8bec3482)
![Screenshot from 2024-04-02
16-05-09](https://github.com/highlight/highlight/assets/1351531/a8d5f4a6-36b6-4d32-8bbf-67a60d68d607)


nextjs
![Screenshot from 2024-04-02
15-02-56](https://github.com/highlight/highlight/assets/1351531/4da91af4-a86d-4084-98bb-a71bf35e5048)

e2e nestjs app, nextjs app
![Screenshot from 2024-04-02
14-45-12](https://github.com/highlight/highlight/assets/1351531/a9a1f90d-223e-47fd-b50b-7227bf311ebc)
![Screenshot from 2024-04-02
14-45-18](https://github.com/highlight/highlight/assets/1351531/ea487dd7-02b7-4a82-b03f-0d423c169da5)
![Screenshot from 2024-04-02
14-51-41](https://github.com/highlight/highlight/assets/1351531/f686a7a6-06a3-4578-8b55-7b686a8b7745)


## Are there any deployment considerations?

changeset

## Does this work require review from our design team?

no