fix ingesting python nested exceptions and python 3.11 trace syntax (#5578)
## Summary

The following is a valid python stacktrace, raised in python 3.11 from
FastAPI
```
Traceback (most recent call last):
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 87, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vkorolik/work/highlight/sdk/highlight-py/highlight_io/sdk.py", line 141, in trace
    yield
  File "/home/vkorolik/work/highlight/sdk/highlight-py/highlight_io/integrations/fastapi.py", line 22, in dispatch
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vkorolik/.cache/pypoetry/virtualenvs/highlight-io-eYcfUyf6-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vkorolik/work/highlight/sdk/highlight-py/e2e/highlight_fastapi/main.py", line 30, in root
    logging.info(f'oh no {5 / 0}')
                          ~~^~~
ZeroDivisionError: division by zero

```

Because of the `During handling of the above exception, another
exception occurred:`, we did not correctly process the stack trace. This
PR fixes this processing.
This PR also supports the [new underline
notation](https://docs.python.org/3/whatsnew/3.11.html#pep-657-fine-grained-error-locations-in-tracebacks)
used in Python 3.11.

## How did you test this change?

New unit test.


![image](https://github.com/highlight/highlight/assets/1351531/72d12dc0-bc48-4842-a193-6a3ecbc5d3dc)


## Are there any deployment considerations?

No