Supporting Next.js middleware (#5392)
## Summary

DragonZSG discovered a problem with `middleware.ts` and
`instrumentation.ts` on [this Discord
thread](https://discord.com/channels/1026884757667188757/1109236631665385473/1109236631665385473)

I was able to reproduce and found this error:

```
An error occurred while loading instrumentation hook: (0 , _highlight_run_next__WEBPACK_IMPORTED_MODULE_1__.registerHighlight) is not a function
```

I was able to resolve the issue with a dynamic import in
`instrumentation.ts`, because it appeared that `middleware.ts` was
attempting to import Node.js-only code in a non-Node.js environment.

I've updated the docs.


![image](https://github.com/highlight/highlight/assets/878947/837d7b43-dd04-463a-896e-b6bc7bd47cf7)

## How did you test this change?

I created a `middleware.ts` file at the root of `e2e/nextjs` and
reproduced the error.

Subsequent changes to `instrumentation.ts` resolved the issue

## Are there any deployment considerations?

Nope